server:
  port: 4000
  
spring:
  application:
    name: InovaProducao
    
  datasource:
    initialization-mode: always
    username: postgres
    url: jdbc:postgresql://localhost:5432/inovaproducoes
    platform: postgres
    password: '061118'
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
uploads:
  bands_folder: bandsImages
  playlist_folder: playlistImages
 
